### ISSUE TITLE
Add --today shortcut option

### ISSUE THREAD

**Issue by asciiascetic** [asciiascetic/nsa#2]
Add an argument `--today` that is just a shorthand for `--time YYYY-MM-DD` for the current day

**Comment by RascalTwo** [comment]
On a unrelated note, I did spend a bit of time trying to get the program working because the database table never initialized, because I first passed `--start` to the program, which created the `.nsa.db` file without creating the actual database.

*****

I'd recommend either:

- Add to the `README.md` that the program should first be ran with the `--daemon` argument.
- Modifying the code so that when running with `--start`, the database is initialized if it's not already.
